{% set name = "CPyCppyy" %}
{% set version = "1.9.4" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cpycppyy/CPyCppyy-{{ version }}.tar.gz
  sha256: 8d31300c33a1a61885d2397cee96e5f0c9ba6cb1afb06f5fcf45d0d629a59d03
  patches:
    - 0001-drop-explicit-instance-declaration.patch

build:
  number: 0
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cppyy-backend
  run:
    - python
    - cppyy-backend

test:
  commands:
    # Importing this extension module is going to fail (it uses some dlopen()
    # magic when cppyy itself is imported.) So we check instead that something
    # has been built at least.
    - ls $SP_DIR/libcppyy*.so

about:
  home: https://pypi.org/project/CPyCppyy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: 'CPython-C++ bindings interface based on Cling/LLVM'
  description: |
    A CPython extension module to access Cling through cppyy-backend.
  doc_url: http://cppyy.readthedocs.io/
  dev_url: https://bitbucket.org/wlav/cpycppyy/src

extra:
  recipe-maintainers:
    - saraedum
    - isuruf
