schema_version: 1

context:
  name: CPyCppyy
  version: 1.12.16

package:
  name: ${{ name | lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cpycppyy/CPyCppyy-${{ version }}.tar.gz
  sha256: 09a845652ac1a82777ec499dda862f54493c1560e9df4cadecda09ecde9e4202

build:
  number: 2
  skip: win
  script: ${{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - if: build_platform != target_platform
      then: python
    - if: build_platform != target_platform
      then: cross-python_${{ target_platform }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-backend ==1.15.2
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-cling ==6.30.0
  run:
    - python
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-backend ==1.15.2
    # cppyy-cling, cppyy-backend, cpycppyy and cppyy are essentially a single package, so we always pin exactly between these.
    - cppyy-cling ==6.30.0

tests:
  - script:
      - ls $SP_DIR/libcppyy*.so

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: CPython-C++ bindings interface based on Cling/LLVM
  description: |
    A CPython extension module to access Cling through cppyy-backend.
  homepage: https://pypi.org/project/CPyCppyy/
  repository: https://bitbucket.org/wlav/cpycppyy/src
  documentation: http://cppyy.readthedocs.io/

extra:
  recipe-maintainers:
    - saraedum
    - isuruf

