travis:
  secure:
    BINSTAR_TOKEN: DyKPF+RdFTcgKMOXsqWOp0/O25I5ybcu6xWnyC87ZHy96COay/qPnQas1iAU1M/+9bv5SVCdkZXM64Mb5BZeIcpSteQNLek5IkkIZrAAv22aOo630eoWSmkQfgA0GmRzV7AI/hUhNsZXIOcbMqdaOm4hvNa71f4HtPxW9h/D11kK7/Z3lBP8AXlu/NChJrYBuuMdLRjyezPePIKjaeYv4EaZFjYX1L2dlMzp62KqZzjat7l8pYt/DtNhfsx0yxOUcMcUHPUp5VCcyIVvF1KWcPHB1z8YfYRGL4DqwXWEtPGqjBtLe3Fw/J7uE4eF0ppDQOPKA3D8Gk+eZVN1zjn0hC5kchlVb442pn9ut3wHlV0yGlnCxhoTl+TM4vK7ASBWwGwEwHSGcoeohU3g1pbeYeEUx+OmrIaS4mhIv2tjcrtpRl6Hwyzu2K6lQFWqBKkDTqjSij1g5Wtpve3i1SD4xlMzuFu0W/3Y1N75IXTidPPu/iY/zUUIZI7AyrIp7Bs/rQuDiLECKcbjfA38U70mniU/LG+ZOwmPMT97kHSqWbzE3ytiP01bf7DD+E1qL4aTXqfsv6jX6u/Xn1BRFReHMcfJvMG0+2WZKEVcaA/nOVixILh6N7xytwQcTGc6PH/l44uGsxVTNqq5OJzwQP8QE2Q404ZBUMXYxoU3um0qJho=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
